### PR TITLE
Update NSCalendarUnit enum format

### PR DESCRIPTION
**Pull request by huguesbr**
Require compiling against iOS8

### CODE REVIEW

**Comment by bertoldofonseca** [comment]
Hey guys. Is this Pull Request dead?

**Comment by billymeltdown** [comment]
Not at all—sorry it's been so long. There are a few to look through, just been a bit busy recently. Will take a look.

**Comment by huguesbr** [comment]
@billymeltdown :+1:

**Comment by billymeltdown** [comment]
Thanks, @huguesbr! @akotulu and @tonimoeckel also submitted patches for this, thanks to them as well.

**Comment by bertoldofonseca** [comment]
First of all, thanks @billymeltdown for the quick response and merge.

But I have another noob question.
I saw that you made a release 1.0.1. How this version goes to CocoaPods? Is it somehow automatic?

**Comment by huguesbr** [comment]
@bertoldofonseca I think they can use the pod command line to submit update on the cocoa pod main repo. ( `pod trunk` command ). 
https://guides.cocoapods.org/making/specs-and-specs-repo.html

PS: typing a comment on github mobile is a pain :)

**Comment by bertoldofonseca** [comment]
@billymeltdown, is there any change to put these changes and last release (v1.0.1) online on CocoaPod soon?

**Comment by billymeltdown** [comment]
@bertoldofonseca sorry, I don't use cocoapods, so I do not know. Happy to accept pull requests.

**Comment by bertoldofonseca** [comment]
Somehow your category is already there. Version: 1.0.0
Maybe some published it there and forgot to tell you.
https://cocoapods.org/pods/NSDate+Helper

**Comment by billymeltdown** [comment]
The podspec was kindly created by @jk back in this issue: https://github.com/billymeltdown/nsdate-helper/issues/8 and I think that page was created automatically as a result.

I've claimed ownership of the project on cocoapods.org, tagging the latest on master branch as 1.0.4. This tag has been pushed to GitHub and an updated podspec for this tag has been published to cocoapods.

**Comment by bertoldofonseca** [comment]
Owwww ... that was quick.
Thanks for all the support @billymeltdown .

**Comment by billymeltdown** [comment]
No problem, it's come up quite a few times and the CocoaPods folks have made it fairly simple to get set up with a bit of reading and futzing around with Ruby. The validate check for compiler warnings is nice, too. Enjoy!

**Pull request merged**
